export const FETCH_UPDATES = "FETCH_UPDATES";
export const FETCH_DIRECTORY = "FETCH_DIRECTORY";
export const FETCH_PROFILE = "FETCH_PROFILE";
export const ADD_UPDATE = "ADD_UPDATE";
export const LOADING_UPDATE = "LOADING_UPDATE";
